services:
  slide-generator:
    build: .
    container_name: slide-generator
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - frontend_net

networks:
  frontend_net:
    external: true
    name: gold-price-monitor_frontend_net
